apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-ltnf
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-830-0005-tenant/ci1t-830-0005-app/devfile-sample-ltnf@sha256:d23796f726f93a7723efccf06e6719ec9cef195d5a4dc2bc4290c0c1d6405b88
        name: my-nodejs
        resources: {}
status: {}
